version: '3.8'

services:
  db:
    image: postgres:11
    volumes:
      - /data/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    image: ch_sag
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001
    restart: always
    volumes:
      - .:/ch-sag
    ports:
      - '8001:8001'    
    depends_on:
      - db

  nginx:
    build: ./nginx
    image: nginx_sh_sag
    volumes:
      - .:/ch-sag
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
