version: '3.8'

services:
  web:
    build: .
    command: gunicorn ch-sag.wsgi:application --bind 0.0.0.0:8001 --timeout 1800
    volumes:
      - .:/ch-sag
    expose:
      - 8001
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/8001
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data: