# Generated by Django 3.1.13 on 2021-09-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworker',
            name='function',
            field=models.CharField(choices=[('Harvest', 'Harvest'), ('Prunning', 'Pruning'), ('Scouting', 'Scouting'), ('Other', 'Other')], default='Other', max_length=8),
        ),
    ]
